name: MLflow CI Retraining

on:
  push:
    branches: [ "main" ]

jobs:
  retrain:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install MLflow (latest)
      run: pip install mlflow>=2.9 docker
      
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Install Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
       auto-update-conda: true
       python-version: "3.10"
       
    - name: Disable MLflow conda activation via source
      run: echo "MLFLOW_DISABLE_ENV_MANAGER_CONDA_WARNING=TRUE" >> $GITHUB_ENV

    - name: Run MLflow Project (Training)
      shell: bash -l {0}
      run: |
       cd MLProject
       mlflow run . --env-manager=conda

    - name: DEBUG â€“ tampilkan isi mlruns
      run: |
       cd MLProject
       echo "===== STRUKTUR mlruns ====="
       find mlruns -type d

    - name: Debug installed packages
      run: pip list

    - name: Debug MLflow artifacts
      run: |
       cd MLProject
       echo "=== MLruns structure ==="
       find mlruns -maxdepth 4

    - name: Build Docker Image with MLflow
      shell: bash -l {0}
      run: |
       cd MLProject

       echo "Find latest MLflow model artifact (entry point = main)..."

       MODEL_PATH=$(ls -td mlruns/0/*/artifacts/main/model | head -1)

       echo "Using MODEL_PATH=$MODEL_PATH"

       mlflow models build-docker \
        -m $MODEL_PATH \
        -n miftah520/heart-mlflow:latest

    - name: Push Docker Image
      run: docker push miftah520/heart-disease-mlflow
