name: MLflow CI Retraining

on:
  push:
    branches: [ "main" ]

jobs:
  retrain:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install MLflow (latest)
      run: pip install mlflow>=2.9 docker
      
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Install Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
       auto-update-conda: true
       python-version: "3.10"
       
    - name: Disable MLflow conda activation via source
      run: echo "MLFLOW_DISABLE_ENV_MANAGER_CONDA_WARNING=TRUE" >> $GITHUB_ENV

    - name: Run MLflow Project (Training)
      shell: bash -l {0}
      run: |
       cd MLProject
       
       mlflow run . --env-manager=conda

       RUN_ID=$(cat run_id.txt)

       echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
       echo "Saved RUN_ID=$RUN_ID"

    - name: Debug installed packages
      run: pip list

    - name: Debug MLflow artifacts
      run: |
       cd MLProject
       echo "=== MLruns structure ==="
       find mlruns -maxdepth 4

    - name: Build Docker Image with MLflow
      shell: bash -l {0}
      run: |
       cd MLProject

       echo "Using RUN_ID=$RUN_ID"

       mlflow models build-docker \
        -m runs:/$RUN_ID/main/model \
        -n ${{ secrets.DOCKER_USERNAME }}/heart-mlflow:latest

    - name: Push Docker Image
      run: docker push miftah520/heart-disease-mlflow
