name: MLflow CI Retraining

on:
  push:
    branches: [ "main" ]

jobs:
  retrain:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install MLflow (latest)
      run: pip install mlflow>=2.9 docker
      
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Install Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
       auto-update-conda: true
       python-version: "3.10"
       
    - name: Disable MLflow conda activation via source
      run: echo "MLFLOW_DISABLE_ENV_MANAGER_CONDA_WARNING=TRUE" >> $GITHUB_ENV

    - name: Run MLflow Project (Training)
      shell: bash -l {0}
      run: |
       cd MLProject
       mlflow run . --env-manager=conda


    - name: Debug installed packages
      run: pip list

    - name: Build Docker Image with MLflow
      shell: bash -l {0}
      run: |
       cd MLProject

       # Ambil run_id TERAKHIR dari mlruns
       RUN_ID=$(mlflow runs list --experiment-id 0 | awk 'NR==2 {print $1}')

       echo "Using RUN_ID=$RUN_ID"

       mlflow models build-docker \
        -m runs:/$RUN_ID/model \
        -n ${{ secrets.DOCKER_USERNAME }}/heart-mlflow:latest

    - name: Push Docker Image
      run: docker push miftah520/heart-disease-mlflow
