name: MLflow CI Retraining

on:
  push:
    branches: [ "main" ]

jobs:
  retrain:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install MLflow (latest)
      run: pip install mlflow>=2.9 docker
      
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Install Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
       auto-update-conda: true
       python-version: "3.10"
       
    - name: Disable MLflow conda activation via source
      run: echo "MLFLOW_DISABLE_ENV_MANAGER_CONDA_WARNING=TRUE" >> $GITHUB_ENV

    - name: Run MLflow Project (Training)
      shell: bash -l {0}
      run: |
       cd MLProject
       mlflow run . --env-manager=conda

    - name: DEBUG â€“ tampilkan isi mlruns
      run: |
       cd MLProject
       echo "===== STRUKTUR mlruns ====="
       find mlruns -type d

    - name: Debug installed packages
      run: pip list

    - name: Debug MLflow artifacts
      run: |
       cd MLProject
       echo "=== MLruns structure ==="
       find mlruns -maxdepth 4

    - name: Build Docker Image with MLflow (from Model Registry)
      run: |
       cd MLProject

       echo "Cari model di MLflow Model Registry..."
       MODEL_DIR=$(ls mlruns/0/models | head -1)

       echo "MODEL_DIR=$MODEL_DIR"

       mlflow models build-docker \
       -m mlruns/0/models/$MODEL_DIR/artifacts \
       -n ${{ secrets.DOCKER_USERNAME }}/heart-disease-mlflow:latest

    - name: Push Docker Image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/heart-disease-mlflow:latest

